#+ endpoint: https://sparql.hegroup.org/sparql?format=text/html
#+ summary: Find pertussis vaccines in OHDSI standard vocabularies with their sources

prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:  <http://www.w3.org/2002/07/owl#>
PREFIX obo:  <http://purl.obolibrary.org/obo/>

SELECT distinct ?VO_ID ?OMOP_Concept_ID ?CVX_code ?RxNorm_CUI ?RxNorm_Extension_ID ?name
FROM <http://purl.obolibrary.org/obo/merged/VO>
WHERE {
	?entity rdfs:subClassOf* obo:VO_0000765 . #pertussis vaccine
	BIND(COALESCE(IF(CONTAINS(STR(?entity), "/obo/"), STRAFTER(STR(?entity), "/obo/"), ?entity))  AS ?VO_ID)
	?entity rdfs:label ?l .
	BIND (str(?l) AS ?name) .
	?entity obo:VO_0010151 ?OMOP_Concept_ID .
    	OPTIONAL { ?entity obo:VO_0005438 ?CVX_code . }
    	OPTIONAL { ?entity obo:VO_0003198 ?RxNorm_CUI . }
    	OPTIONAL { ?entity obo:VO_0010152 ?RxNorm_Extension_ID . }
}
ORDER BY ASC(?OMOP_Concept_ID)
